#! /bin/bash
cd ~/Documents/Projects/Git/factory-tree/server
npm run build-docker-prod
docker tag factory-tree-server:prod 803115477085.dkr.ecr.us-east-2.amazonaws.com/factory-tree-server:prod
# $(aws ecr get-login --no-include-email --region us-east-2)
docker push 803115477085.dkr.ecr.us-east-2.amazonaws.com/factory-tree-server:prod